# Generated by Django 5.2.7 on 2025-12-10 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passengerprofile',
            name='date_of_birth',
            field=models.DateField(default='0000-00-00'),
        ),
        migrations.AlterField(
            model_name='passengerprofile',
            name='passport',
            field=models.CharField(blank=True, max_length=9, null=True, unique=True),
        ),
    ]
