# Generated by Django 5.2.7 on 2025-12-10 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_passengerprofile_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passengerprofile',
            name='date_of_birth',
            field=models.DateField(default='1900-01-01'),
        ),
    ]
