# Generated by Django 5.2.7 on 2025-12-10 13:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_passengerprofile_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='hire_date',
            field=models.DateField(default=datetime.date(2025, 12, 10)),
        ),
    ]
