# Generated by Django 5.2.7 on 2025-12-10 13:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_admin_hire_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='hire_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
